### ISSUE TITLE
No HEIC support, despite option being included

### ISSUE THREAD

**Issue by nkalvi** [blogabe/homebrew-xplanet#6]
https://github.com/blogabe/homebrew-xplanet/blob/1c53b7683a8ea01e8d649f5bcb87a0e3f3d1f309/imagemagick.rb#L13

I don't think there's an issue with the tap itself, but I want to raise the issue here.

I'm wondering why HEIC is missing among the formats, though all the dependencies are there (no errors during the installation.)

**Comment by blogabe** [comment]
I never intended to support imagemagick on this tap, but Homebrew's changes to formula options kind of forced my hand.  There may be other taps hosting what you're looking for, but it sounds like you're asking to simply make this a default rather than an option?

I'm fine with that.  I copied the last known imagemagick formula from Homebrew prior to their changes and have for the most part only updated it with imagemagick release updates.

Please confirm and I can make the change when I get a few or you can submit a pull request and I can merge it in.

**Comment by nkalvi** [comment]
Thanks for the prompt reply.

Yes, could you please make this default? (since we cannot specify any options now)

**Comment by blogabe** [comment]
Editing my prior response as I was unsure what you were referring to at first.

**Comment by blogabe** [comment]
I removed the option and enabled HEIC by default in the compile time options.
